export const sanphamphukien = [
  {
    id: 1,
    img: "./public/tainguyen/pkLS2rapid.jpg",
    name: "Mũ Bảo Hiểm LS2 Rapid FF353",
    price: "1700000",
  },
  {
    id: 2,
    img: "./public/tainguyen/pkls2thunder.jpg",
    name: "Mũ Bảo Hiểm LS2 Thunder FF805 GP Racing Carbon",
    price: "11900000",
  },
  {
    id: 3,
    img: "./public/tainguyen/pkpkagvax-9.png",
    name: "Mũ Bảo Hiểm AGV AX-9",
    price: "16990000",
  },
  {
    id: 4,
    img: "./public/tainguyen/pkagvorbyt.png",
    name: "Mũ Bảo Hiểm AGV Orbyt",
    price: "3990000",
  },
  {
    id: 5,
    img: "./public/tainguyen/pkagvk6.jpg",
    name: "Mũ Bảo Hiểm AGV k6",
    price: "12990000",
  },
  {
    id: 6,
    img: "./public/tainguyen/pkagvk3sv.png",
    name: "Mũ Bảo Hiểm AGV K3 SV",
    price: "5990000",
  },
  {
    id: 7,
    img: "./public/tainguyen/pkhjcv60.jpg",
    name: "Mũ Bảo Hiểm HJC V60 ",
    price: "7300000 - 7800000",
  },
  {
    id: 8,
    img: "./public/tainguyen/pkhjcv31.jpg",
    name: "Mũ Bảo Hiểm HJC V31",
    price: "5400000",
  },
  {
    id: 9,
    img: "./public/tainguyen/pkhjcismax2.jpg",
    name: "Mũ Bảo Hiểm HJC IS-MAX II",
    price: "3900000",
  },
  {
    id: 10,
    img: "./public/tainguyen/pkhjci50.jpg",
    name: "Mũ Bảo Hiểm HJC i50",
    price: "4250000",
  },
  {
    id: 11,
    img: "./public/tainguyen/pkhjci30.jpg",
    name: "Mũ Bảo Hiểm HJC i30",
    price: "4500000",
  },
  {
    id: 12,
    img: "./public/tainguyen/pkhjci71.jpg",
    name: "Mũ Bảo Hiểm HJC i71",
    price: "6300000",
  },
  {
    id: 13,
    img: "./public/tainguyen/pkhjcf-70.png",
    name: "Mũ Bảo Hiểm HJC F-70",
    price: "9100000",
  },
  {
    id: 14,
    img: "./public/tainguyen/pkhjccs-15.jpg",
    name: "Mũ Bảo Hiểm HJC CS-15 Cho Nữ Biker",
    price: "2900000",
  },
  {
    id: 15,
    img: "./public/tainguyen/pkhjccool.jpg",
    name: "Mũ Bảo Hiểm HJC COOL Plus",
    price: "1400000",
  },
  {
    id: 16,
    img: "./public/tainguyen/pkkawasakilanyard.png",
    name: "KAWASAKI LANYARD",
    price: "Liên hệ",
  },
  {
    id: 17,
    img: "./public/tainguyen/pkkawasakileatherkeychain.jpg",
    name: "KAWASAKI LEATHER KEY CHAIN (NINJA)",
    price: "Liên hệ",
  },
  {
    id: 18,
    img: "./public/tainguyen/pkwpbackpack.jpg",
    name: "WP BACK PACK",
    price: "Liên hệ",
  },
  {
    id: 19,
    img: "./public/tainguyen/pkkawasakiwatch02.jpg",
    name: "KAWASAKI WATCH MODEL 02",
    price: "Liên hệ",
  },
  {
    id: 20,
    img: "./public/tainguyen/pkkawasakiwatch01.jpg",
    name: "KAWASAKI WATCH MODEL 01",
    price: "Liên hệ",
  },
  {
    id: 21,
    img: "./public/tainguyen/pkspiritairmesh.jpg",
    name: "SPIRIT AIR MESH JACKET WHT/BLK",
    price: "Liên hệ",
  },
  {
    id: 22,
    img: "./public/tainguyen/pkspritairmesh-grn-blk.jpg",
    name: "SPIRIT AIR MESH JACKET GRN/BLK ",
    price: "Liên hệ",
  },
  {
    id: 23,
    img: "./public/tainguyen/pkbeaniejonathanrea.jpg",
    name: "KAWASAKI BEANIE JONATHAN REA ",
    price: "Liên hệ",
  },
  {
    id: 24,
    img: "./public/tainguyen/pkbeanietomsykes.jpg",
    name: "KAWASAKI BEANIE TOM SYKES",
    price: "Liên hệ",
  },
  {
    id: 25,
    img: "./public/tainguyen/pksportscap.jpg",
    name: "SPORTS CAP (1 SIZE)",
    price: "Liên hệ",
  },
  {
    id: 26,
    img: "./public/tainguyen/pksbk2021cap.png",
    name: "SBK 2021 CAP",
    price: "Liên hệ",
  },
  {
    id: 27,
    img: "./public/tainguyen/pkfreedomkawasakisneakers.jpg",
    name: "FREEDOM KAWASAKI SNEAKERS ",
    price: "Liên hệ",
  },
  {
    id: 28,
    img: "./public/tainguyen/pkzx5kboost.jpg",
    name: "ZX 5K BOOST KAWASAKI ",
    price: "Liên hệ",
  },

  {
    id: 29,
    img: "./public/tainguyen/pkhjccs-max-zealot.jpg",
    name: "Mũ Bảo Hiểm HJC CS-MX ZEALOT",
    price: "2500000",
  },
  {
    id: 30,
    img: "./public/tainguyen/pkhjcds-x1.png",
    name: "Mũ Bảo Hiểm HJC DS-X1",
    price: "4350000",
  },
  {
    id: 31,
    img: "./public/tainguyen/pkhjc-c-90.jpg",
    name: "Mũ Bảo Hiểm HJC C-90",
    price: "4050000",
  },
  {
    id: 32,
    img: "./public/tainguyen/pkhjc-c-10-fabioquartararo.jpg",
    name: "Mũ Bảo Hiểm HJC C-10 Fabio Quartararo",
    price: "3750000",
  },
  {
    id: 33,
    img: "./public/tainguyen/pkhjc-c-70.png",
    name: "Mũ Bảo Hiểm HJC C-70",
    price: "3900000",
  },
  {
    id: 34,
    img: "./public/tainguyen/pkhjc-i-70.jpg",
    name: "Mũ Bảo Hiểm HJC i-70",
    price: "5990000",
  },
  {
    id: 35,
    img: "./public/tainguyen/pktuichongnuoc40litea115bk.jpg",
    name: "TÚI CHỐNG NƯỚC 40 LIT EA115BK",
    price: "1630000 ",
  },
  {
    id: 36,
    img: "./public/tainguyen/pk46lit-dolomiti-dlm46b.jpg",
    name: "THÙNG SAU 46 LIT TREKKER DOLOMITI DLM46B",
    price: "12600000",
  },
  {
    id: 37,
    img: "./public/tainguyen/pk42lit-outback-obkn42a.jpg",
    name: "THÙNG SAU 42 LIT TREKKER OUTBACK OBKN42A",
    price: "11810000 ",
  },
  {
    id: 38,
    img: "./public/tainguyen/pkhonge23g730-s_or.jpg",
    name: "THÙNG CẶP HÔNG E23G730-S_OR",
    price: "3680000 ",
  },
  {
    id: 39,
    img: "./public/tainguyen/pk42lit-obkn42b.jpg",
    name: "THÙNG SAU 42 LIT TREKKER OUTBACK OBKN42B",
    price: "12720000 ",
  },
  {
    id: 40,
    img: "./public/tainguyen/pkb27nmal.jpg",
    name: "THÙNG SAU B27NMAL",
    price: "910000 ",
  },
  {
    id: 41,
    img: "./public/tainguyen/pkdlm36apack2.jpg",
    name: "THÙNG HÔNG DLM36APACK2",
    price: "19920000 ",
  },
  {
    id: 42,
    img: "./public/tainguyen/pkb32n.jpg",
    name: "THÙNG SAU B32N",
    price: "1280000 ",
  },
  {
    id: 43,
    img: "./public/tainguyen/pkdlm36bpack2.jpg",
    name: "THÙNG HÔNG DLM36BPACK2",
    price: "21910000 ",
  },
  {
    id: 44,
    img: "./public/tainguyen/pk37lit-obkn37apack2.jpg",
    name: "THÙNG CẶP HÔNG 37 LIT TREKKER OUTBACK OBKN37APACK2",
    price: "22830000 ",
  },
  {
    id: 45,
    img: "./public/tainguyen/pkb32n-adv.jpg",
    name: "THÙNG SAU B32N-ADV",
    price: "1810000 ",
  },
  {
    id: 46,
    img: "./public/tainguyen/pk37lit-obkn37bpack2.jpg",
    name: "THÙNG CẶP HÔNG 37 LIT TREKKER OUTBACK OBKN37BPACK2",
    price: "24380000 ",
  },
  {
    id: 47,
    img: "./public/tainguyen/pkb42n-antartice.jpg",
    name: "THÙNG SAU B42N ANTARTICA ",
    price: "2500000 ",
  },
  {
    id: 48,
    img: "./public/tainguyen/pkalaska.jpg",
    name: "THÙNG CẶP HÔNG TREKKER ALASKA",
    price: "15870000 ",
  },
  {
    id: 49,
    img: "./public/tainguyen/pke43ntl.jpg",
    name: "THÙNG SAU E43NTL",
    price: "1400000 ",
  },
];
